<?php
/**
 * Implements hook_node_view().
 *
 * Adds a Facebook like button to page nodes.
 */
function product_extend_node_view($node, $view_mode, $langcode) {
    $node->content['social_buttons'] = array(
      '#type' => 'item',
      '#title' => '',
      '#markup' =>  theme('social_buttons', array(
        'node' => null)),
      '#attributes' => array('class' => array('social-buttons')),
    );
    $node->content['facebook_comment'] = array(
      '#type' => 'item',
      '#title' => '',
      '#markup' =>  '<div class="fb-comments" data-width="100%" data-numposts="5"></div>',
      '#attributes' => array('class' => array('comments')),
    );
    $node->content['created'] = array(
      '#type' => 'item',
      '#title' => '',
      '#markup' =>  '<span class="created">'.format_date($node->created).'</span>',
      '#attributes' => array('class' => array('created')),
    );
    switch ($node->type) {
      case 'story':
        $node->content['news_title'] = array(
          '#type' => 'item',
          '#title' => '',
          '#markup' =>  '<h1 class="content-title">'.$node->title.'</h1>',
          '#attributes' => array('class' => array('news-title')),
        );

        $block = block_load('views', 'chapter-block');
        $block=_block_get_renderable_array(_block_render_blocks(array($block)));
        $block_title=$block['views_chapter-block']['#block']->subject;
        $block['views_chapter-block']['#block']->subject=$block_title.' '.$node->title;
        $output = drupal_render($block);
        $node->content['newest_chapters'] = array(
          '#type' => 'item',
          '#title' => '',
          '#markup' =>  $output,
          '#attributes' => array('class' => array('newest-chapters')),
        );

        $block = block_load('views', 'chapter-block_all');
        $block=_block_get_renderable_array(_block_render_blocks(array($block)));

        $block_title=$block['views_chapter-block_all']['#block']->subject;
        $block['views_chapter-block_all']['#block']->subject=$block_title.' '.$node->title;
        $output = drupal_render($block);
        $node->content['chapters'] = array(
          '#type' => 'item',
          '#title' => '',
          '#markup' =>  $output,
          '#attributes' => array('class' => array('chapters')),
        );

        $user = user_load($node->uid);
        $output='<div class="field-user"><a href="'.url('user/'.$user->uid).'">'.$user->name.'</a></div>';
        $node->content['user'] = array(
          '#type' => 'item',
          '#title' => '',
          '#markup' =>  $output,
          '#attributes' => array('class' => array('chapters')),
        );
        //
        break;

      case 'chapter':
        $node->content['news_title'] = array(
          '#type' => 'item',
          '#title' => '',
          '#markup' =>  '<h1 class="content-title">'.$node->title.'</h1>',
          '#attributes' => array('class' => array('news-title')),
        );
        $field_story=field_get_items('node',$node,'field_story');
        $field_author=field_get_items('node',$field_story[0]['entity'],'field_author');
        $author=node_load($field_author[0]['target_id']);

        $node->content['author'] = array(
          '#type' => 'item',
          '#title' => '',
          '#markup' =>  '<div class="author"><a href="'.url('node/'.$author->nid).'">'.$author->title.'</a></div>',
          '#attributes' => array('class' => array('author')),
        );
        break;
      default:
        break;
    }
}

/**
 * Implements hook_field_extra_fields().
 *
 * Declare our Facebook Like button as a pseudo-field.
 */
function product_extend_field_extra_fields() {

    $extra['node']['story']['display'] = array(
      'news_title' => array(
        'label' => t('Title'),
        'description' => t('Title.'),
        'weight' => 1,
      ),
      'created' => array(
        'label' => t('Created date'),
        'description' => t('created date.'),
        'weight' => 1,
      ) ,
      'social_buttons' => array(
        'label' => t('social_buttons'),
        'description' => t('social_buttons'),
        'weight' => 1,
      ),
      'facebook_comment' => array(
        'label' => t('Facebook comment'),
        'description' => t('Facebook comment'),
        'weight' => 1,
      ),
       'chapters' => array(
        'label' => t('chapters'),
        'description' => t('chapters'),
        'weight' => 1,
      ),
       'newest_chapters' => array(
        'label' => t('Newest chapters'),
        'description' => t('Newest chapters'),
        'weight' => 1,
      ),
       'user' => array(
        'label' => t('User'),
        'description' => t('User'),
        'weight' => 1,
      )
    );

    $extra['node']['chapter']['display'] = array(
      'news_title' => array(
        'label' => t('Title'),
        'description' => t('Title.'),
        'weight' => 1,
      ),
     'author' => array(
        'label' => t('Author'),
        'description' => t('Author.'),
        'weight' => 1,
      ),
      'social_buttons' => array(
        'label' => t('social_buttons'),
        'description' => t('social_buttons'),
        'weight' => 1,
      ),
      'facebook_comment' => array(
        'label' => t('Facebook comment'),
        'description' => t('Facebook comment'),
        'weight' => 1,
      ),
      'created' => array(
        'label' => t('Created date'),
        'description' => t('created date.'),
        'weight' => 1,
      ) ,
    );


  return $extra;
}


/**
 * Implements hook_theme().
 */
function product_extend_theme() {
  return array(
    'social_buttons' => array(
      'variables' => array(
        'node' => NULL,
      ),
      'template' => 'templates/social-buttons',
    ),
  );
}