<?php

define('IMPORTED_NONE',0);
define('IMPORTED_STORY',1);
define('IMPORTED_STORY_CHAPTER',2);

/**
 * Implements hook_init().
 */
function thuypx_import_init() {
  if (current_path() == 'thuypx_import/story' || current_path() == 'thuypx_import/chapter') {
    drupal_page_is_cacheable(FALSE);
  }
}

function thuypx_import_menu() {
    $items['thuypx_import/story'] = array(
        'type' => MENU_CALLBACK,
        'page callback' => 'thuypx_import_story',
        'access arguments' => array('access content'),
    );
    $items['thuypx_import/chapter'] = array(
        'type' => MENU_CALLBACK,
        'page callback' => 'thuypx_import_chapter',
        'access arguments' => array('access content'),
    );
    $items['thuypx_import/clean-chapter'] = array(
        'type' => MENU_CALLBACK,
        'page callback' => 'thuypx_import_clean_chapter',
        'access arguments' => array('access content'),
    );

    $items['thuypx_import/clean-weight-chapter'] = array(
      'type' => MENU_CALLBACK,
      'page callback' => 'thuypx_import_clean_weight_chapter',
      'access arguments' => array('access content'),
    );

  $items['thuypx_import/story-update-status'] = array(
    'type' => MENU_CALLBACK,
    'page callback' => 'thuypx_import_story_update_status',
    'access arguments' => array('access content'),
  );
    return $items;
}
function thuypx_import_story_update_status(){
  require_once DRUPAL_ROOT.'/tools/simplehtmldom_1_5/simple_html_dom.php';
  require_once DRUPAL_ROOT.'/tools/libs/helper.php';

  $file=DRUPAL_ROOT.'/story1_nid.txt';
  $nid=(int)file_get_contents($file);
  $q="SELECT * FROM `crawl_story` WHERE `nid`>{$nid} ORDER BY `nid` ASC LIMIT 1";
  $row=db_query($q)->fetchAssoc();
  if(!$row){
    echo "done";
    exit();
  }
  $helper=new helper();
  $html_str =$helper->curl_download($row['url_source']);
  $html = new simple_html_dom();
  $html->load($html_str);
  $nid=$row['nid'];

    file_put_contents($file,$nid);
  $node=node_load($nid);


  $status=trim(strip_tags($html->find('.detail-info ul',0)->find('li', 3)->plaintext));
  if($status=='Đang cập nhật'){
    $node_wrapper = entity_metadata_wrapper('node', $node);
    $node_wrapper->field_state->set(1);
  }else{
    $node_wrapper = entity_metadata_wrapper('node', $node);
    $node_wrapper->field_state->set(2);
  }
  $node_wrapper->save();

  echo url('node/'.$nid,array('absolute'=>true));
  echo '<br/>';
  echo $status;
}


function thuypx_import_clean_weight_chapter(){
  $file=DRUPAL_ROOT.'/story_nid.txt';
  $nid=(int)file_get_contents($file);
  $q="SELECT `nid` FROM `node` WHERE `nid`>{$nid} AND type='story' ORDER BY `nid` ASC LIMIT 1";
  $nid=db_query($q)->fetchField();
  if(!$nid){
    echo "done";
    exit();
  }

  file_put_contents($file,$nid);
  $sql="SELECT DISTINCT node.nid AS nid, node.title AS node_title, history.timestamp AS history_timestamp, node.created AS node_created, node.changed AS node_changed, node.type AS node_type, node.status AS node_status
    FROM 
    node node
    LEFT JOIN field_data_field_story field_data_field_story ON node.nid = field_data_field_story.entity_id AND (field_data_field_story.entity_type = 'node' AND field_data_field_story.deleted = '0')
    LEFT JOIN history history ON node.nid = history.nid AND history.uid = '1'
    WHERE (( (field_data_field_story.field_story_target_id = '{$nid}' ) )AND(( (node.type IN  ('chapter')) )))
    ORDER BY node_changed DESC
    LIMIT 50 OFFSET 0";
    $count_chapter=db_query($sql)->rowCount();
    if($count_chapter<1){
      db_query("UPDATE crawl_story SET status=2 WHERE nid={$nid}");
    }
    echo "story id: {$nid}, chapters: {$count_chapter}";

}

function thuypx_import_clean_chapter(){
    $file=DRUPAL_ROOT.'/story_nid.txt';
    $nid=(int)file_get_contents($file);
    $q="SELECT `nid` FROM `node` WHERE `nid`>{$nid} AND type='story' ORDER BY `nid` ASC LIMIT 1";
    $nid=db_query($q)->fetchField();
    if(!$nid){
        echo "done";
        exit();
    }


    $q="SELECT node.title , node.nid AS nid
        FROM 
        `node` node
        LEFT JOIN `field_data_field_story` field_data_field_story ON node.nid = field_data_field_story.entity_id AND (field_data_field_story.entity_type = 'node' AND field_data_field_story.deleted = '0')
        WHERE (( (node.status = '1') AND (node.type IN  ('chapter')) AND (field_data_field_story.field_story_target_id = '{$nid}') ))
        ";
        $chapters=db_query($q);
        $data=array();
        while ($chapter=$chapters->fetch()){
            if(!isset($data[$chapter->title])) $data[$chapter->title]=array();
            $data[$chapter->title][]=$chapter->nid;
        }
        $deleted=0;
        foreach($data as $items){
            if(count($items)>1){
                array_shift($items);
                $deleted+=count($items);
                node_delete_multiple($items);
            }
        }
        echo url('node/'.$nid,array('absolute'=>true));
        echo '<br/>';
        echo 'Clear: '.$deleted;
        echo '<br/>';
        print_r($data);
        file_put_contents($file,$nid);
    }


function thuypx_import_story() {
    $databases=array (
        'database' => 'truyenthegioi_com',
        'username' => 'truyenthegioi_co',
        'password' => 'Sta9D3#23tM9aj',
        'host' => 'localhost',
        'port' => '',
        'driver' => 'mysql',
        'prefix' => '',
    );

    //get term
    require_once DRUPAL_ROOT."/tools/libs/database/MysqliDb.php";
    $db = new MysqliDb ($databases['host'],$databases['username'], $databases['password'],$databases['database'],3306,'utf8');
    $db->where('status',1);
    $db->where('imported',IMPORTED_NONE);
    $story=$db->getOne('crawl_story');
        
    if(!$story){
        echo "completed";
        return;
        exit();
    }     

    //update status imported
    $db->where ('id',$story['id']);
    $db->update('crawl_story',array('imported'=>IMPORTED_STORY));


    //taxonomy term
    $term=taxonomy_get_term_by_name($story['category'],'category');
    if(count($term)<1){
        $term = new stdClass();
        $term->name = $story['category'];
        $term->vid = 2;
        taxonomy_term_save($term);
    }else{
        $term=array_shift($term);
    }

    //author
    $authors = node_load_multiple(NULL, array("type"=>"author","title" => $story['author']));
    if(count($authors)<1){
        $author = new stdClass();
        $author->title = $story['author'];
        $author->type = "author";
        node_object_prepare($author);
        node_save($author);
    }else{
        $author = array_shift($authors);
    }

    $node = new stdClass();
    $node->title = $story['title'];
    $node->type = "story";
    node_object_prepare($node); // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
    $node->language = LANGUAGE_NONE; // Or e.g. 'en' if locale is enabled
    $node->uid = 1;
    $node->status = 0; //(1 or 0): published or not
    $node->promote = 0; //(1 or 0): promoted to front page
    $node->comment = 2; // 0 = comments disabled, 1 = read only, 2 = read/write

    #image
    $existing_filepath = $story['image'];
    //if(file_exists($existing_filepath)){
        $new_filepath = "public://".basename($story['image']);
        $drupal_file = file_save_data(file_get_contents($existing_filepath), $new_filepath);
        $drupal_file->alt = $node->title;
        $drupal_file->title = $node->title;
        $node->field_image[$node->language][0] = get_object_vars($drupal_file);
    //};


//summary

    $node->body[$node->language][0]['format']  = 'full_html';
    $node->body[$node->language][0]['value']  = $story['detail'];

    #start
    $node->field_state[$node->language][0]['value']  = $story['state'];

    #category
    $node->field_category[LANGUAGE_NONE][0]['tid']=$term->tid;

    #author
    $node->field_author[LANGUAGE_NONE][0]['target_id']=$author->nid;

    $node = node_submit($node); // Prepare node for saving


    node_save($node);

    //update status imported
    $db->where ('id',$story['id']);
    $db->update('crawl_story',array('nid'=>$node->nid));
    //update story_nid on chapter table
    $db->where ('story_id',$story['id']);
    $db->update('crawl_story_chapter',array('story_nid'=>$node->nid));
    echo 'done!';
    exit();

}

function thuypx_import_chapter() {
    $databases=array (
        'database' => 'truyenthegioi_com',
        'username' => 'truyenthegioi_co',
        'password' => 'Sta9D3#23tM9aj',
        'host' => 'localhost',
        'port' => '',
        'driver' => 'mysql',
        'prefix' => '',
    );

    require_once DRUPAL_ROOT."/tools/libs/helper.php";
    require_once DRUPAL_ROOT."/tools/simplehtmldom_1_5/simple_html_dom.php";
    require_once DRUPAL_ROOT."/tools/libs/database/MysqliDb.php";
    $db = new MysqliDb ($databases['host'],$databases['username'], $databases['password'],$databases['database'],3306,'utf8');

    $db->where('status',0);
    $db->where('story_nid',0,'>');
    if(isset($_GET['start_id'])){
      $start_id=(int)$_GET['start_id'];
      $db->where('id',$start_id,'>');
    }
    $chapter=$db->getOne('crawl_story_chapter');
    if(!$chapter){
        echo "completed";
        return;
        exit();
    }


    //update status imported
    $db->where ('id',$chapter['id']);
    $db->update('crawl_story_chapter',array('status'=>1));

    $helper=new helper();

    $html_str=$helper->curl_download($chapter['url_source']);
    $html = new simple_html_dom();
    $html->load($html_str);
    $body=$html->find('#content',0)->innertext;
    $body=preg_replace('#<script(.*?)>(.*?)</script>#is', '', $body);
    $body=strip_tags($body,'<p><br>');

    $node = new stdClass();
    $node->title = $chapter['title'];
    $node->type = "chapter";
    node_object_prepare($node); // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
    $node->language = LANGUAGE_NONE; // Or e.g. 'en' if locale is enabled
    $node->uid = 1;
    $node->status = 1; //(1 or 0): published or not
    $node->promote = 0; //(1 or 0): promoted to front page
    $node->comment = 2; // 0 = comments disabled, 1 = read only, 2 = read/write

    $node->body[$node->language][0]['format']  = 'full_html';
    $node->body[$node->language][0]['value']  = $body;

    $node->field_weight[LANGUAGE_NONE][0]['value']=$chapter['weight'];
    $node->field_story[LANGUAGE_NONE][0]['target_id']=$chapter['story_nid'];

    $node = node_submit($node); // Prepare node for saving
    node_save($node);

    echo 'chapter: '.$chapter['id'].' done!';
    exit();

}

function thuypx_import_search_api_views_query_alter(&$view, &$query) {
  if ($view->name == 'tim_kiem_author') {
      $where=&$query->where;
      $where[1]['conditions'][0][1]=$_GET['title'];
  }
}

function thuypx_import_views_pre_execute(&$view) {
  if ($view->name == 'tim_kiem') {
    if(isset($_GET['field_category']) AND isset($_GET['field_state'])){
      if($_GET['field_category']!='All' OR $_GET['field_state']!='All'){
        $header =&$view->header;
        unset($header['view']);
        unset($header['area_1']);
      }
    }
  }
}

function thuypx_import_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'user_login_block' || $form_id == 'user_login') {

      $form['actions']['submit']['#suffix']= '<div class="extend-login-form">'. '
        <div class="user-password"><a href="/user/password">Quên mật khẩu</a></div>
        <div class="user-facebook login"><a href="/user/simple-fb-connect"><i class="fa fa-facebook"></i> facebook login</a></div>
        <div class="user-register">Chưa có tài khoản? <a href="/user/register">Đăng Ký</a></div>
        '.'</div>';
  }
}